### ISSUE TITLE
refactor: delete unused UserAccountModel

### ISSUE THREAD

**Issue by yoonjikimkr** [sc2bat/my_flutter_image_searching_app_cleanarch#93]
supabase test 용도였던 것으로 보이는 UserAccountModel #20 삭제?

**Comment by sc2bat** [comment]
현재 사용하지 않는 것으로 판단되며 삭제해도 무방할 것 같습니다

**Comment by yoonjikimkr** [comment]
Develop에서 UserAccountModel 삭제했습니다. 이후 새 branch로 checkout했습니다.
